### ISSUE TITLE
Can't change codeblock "settings"

### ISSUE THREAD

**Issue by ryanbuck182** [Amp63/pyre#5]
So you know the item in the bottom right of some codeblocks that let you change a setting or something? E.g. a control block set to wait allows you to change if the wait is in ticks, seconds, or minutes. In-game, this is called a tag, so perhaps codeblock tag is the correct term. Anyway, there doesn't seem to be a method of setting these codeblock tags. If I generate a script from a template containing a codeblock with a codeblock tag, then build and send the script, the template built from the generated script sets any codeblock tags back to their default value. This isn't really a bug, it's more of a feature that could be implemented and just hasn't yet. But yeah just figured I'd let you know.

**Comment by Amp63** [comment]
Yeah, I've been meaning to add this feature for a while, so I'll implement it in the next update. Thanks!

**Comment by RyanBuck182** [comment]
Something I've recently found is that `t.player_action('ScoreDefFormat')` is broken, no matter how you use it, and I believe it's because it's completely missing it's codeblock tag. Other blocks I've tested still have the codeblock tag, just set to it's default value, but that one spawns completely without it. Also thanks for being active and fixing the bugs I've been finding, I appreciate it.

**Comment by Amp63** [comment]
Added in 0.7.0.
